config/routes.rb
Rails.application.routes.draw do
  cms_fortress_routes :path => '/cms-admin'

  namespace :admin do
    resources :episodes
  end

  resources :episodes

  comfy_route :cms_admin, :path => '/admin'
  comfy_route :cms, :path => '/', :sitemap => false

end

app/models/episode.rb
class Episode < ActiveRecord::Base

  # -- Relationships --------------------------------------------------------


  # -- Callbacks ------------------------------------------------------------


  # -- Validations ----------------------------------------------------------
  validates :title, :content, :presence => true

  # -- Scopes ---------------------------------------------------------------


  # -- Class Methods --------------------------------------------------------


  # -- Instance Methods -----------------------------------------------------
  def published
  	
  end

end

app/controllers/admin/episodes_controller.rb
class Admin::EpisodesController < Comfy::Admin::Cms::BaseController

  before_action :build_episode,  :only => [:new, :create]
  before_action :load_episode,   :only => [:show, :edit, :update, :destroy]

  def index
    @episodes = Episode.order("id DESC").page(params[:page])
  end

  def show
    render
  end

  def new
    render
  end

  def edit
    render
  end

  def create
    @episode.save!
    flash[:success] = 'Episode created'
    redirect_to :action => :show, :id => @episode
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to create Episode'
    render :action => :new
  end

  def update
    @episode.update_attributes!(episode_params)
    flash[:success] = 'Episode updated'
    redirect_to :action => :show, :id => @episode
  rescue ActiveRecord::RecordInvalid
    flash.now[:danger] = 'Failed to update Episode'
    render :action => :edit
  end

  def destroy
    @episode.destroy
    flash[:success] = 'Episode deleted'
    redirect_to :action => :index
  end

protected

  def build_episode
    @episode = Episode.new(episode_params)
  end

  def load_episode
    @episode = Episode.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:danger] = 'Episode not found'
    redirect_to :action => :index
  end

  def episode_params
    params.fetch(:episode, {}).permit(:title, :content, :is_published)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < Comfy::Cms::ContentController
	helper :Episodes

def index
	@episodes = Episode.where(:is_published => 1).order("id DESC")
	render :cms_layout => 'page'
end

def show
	@episode = Episode.find(params[:id])
	@id = @episode.id
	render :cms_layout => 'episode'
end

end

app/helpers/application_helper.rb
module ApplicationHelper
	include EpisodesHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper

	def nav_arrows(id)
		back = id - 1
		forward = id + 1
		html = ''

		html << %Q{<span class="back">}
		if back > 0
			html << link_to("", Episode.find(back), {:class => "back"})
		else 
			html << link_to("", "", {:class => "oldest"})
		end
		html << %Q{</span>}
		html << %Q{<span class="forward">}
		unless forward > Episode.last.id
			html << link_to("", Episode.find(forward), {:class => "forward"})
		else
			html << link_to("", "#", {:class => "newest"})
		end
		html << %Q{</span>}
		return html.html_safe
	end

	def show_current
		@episode = Episode.where(:is_published => 1).last
		@id = @episode.id
		render 'episodes/current'
	end
end

app/views/admin/episodes/_form.html.erb
<%= form.text_field :title %>
<%= form.text_area :content, :data => {'cms-rich-text' => true} %>
<%= form.check_box :is_published %>
<%= form.form_group :class => 'form-actions' do %>
  <%= form.submit :class => 'btn btn-primary' %>
<% end %>

app/views/admin/episodes/edit.html.erb
<div class="page-header">
  <h2>Edit Episode</h2>
</div>
<%= comfy_form_for [:admin, @episode] do |form| %>
  <%= render form %>
<% end %>

app/views/admin/episodes/index.html.erb
<div class="page-header">
  <%= link_to 'New Episode', new_admin_episode_path, :class => 'btn btn-default pull-right' %>
  <h2>Episodes</h2>
</div>
<%= paginate @episodes, :theme => 'comfy' %>
<table class="table table-hover table-bordered">
  <tr>
    <th></th>
    <th class="main">Title</th>
    <th>Published?</th>
    <th></th>
  </tr>
  <% @episodes.each do |episode| %>
    <tr>
      <td>#<%= episode.id %></td>
      <td class="main"><%= episode.title %></td>
      <td>
        <%= episode.is_published %>
      </td>
      <td>
        <div class="btn-group btn-group-sm">
          <%= link_to 'Edit', edit_admin_episode_path(episode), :class => 'btn btn-default' %>
          <%= link_to 'Delete', admin_episode_path(episode), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %>
        </div>
      </td>
    </tr>
  <% end %>
</table>
<%= paginate @episodes, :theme => 'comfy' %>

app/views/admin/episodes/new.html.erb
<div class="page-header">
  <h2>New Episode</h2>
</div>
<%= comfy_form_for [:admin, @episode] do |form| %>
  <%= render form %>
<% end %>

app/views/admin/episodes/show.html.erb
<div class="page-header">
  <h2>Episode <%= @episode.id %>: <%= @episode.title %></h2>
</div>
<div class="content">
	<%= @episode.content.html_safe %>
</div>

app/views/comfy/admin/cms/partials/_navigation_inner.html.haml
%li= active_link_to 'Episodes', admin_episodes_path

app/views/episodes/_current.html.erb
<div class="page-header small-12 medium-12 large-12 columns">
  <h1>Episode <%= @episode.id %>: <%= @episode.title %></h1>
</div>
<div class="content small-12 medium-12 large-12 columns">
	<%= @episode.content.html_safe %>
</div>
<div class="prev-next small-12 medium-12 large-12 columns">
	<%= nav_arrows(@id) %>
</div>
<div class="comments small-12 medium-12 large-12 columns">
	<div id="disqus_thread"></div>
	<script type="text/javascript">
	    /* * * CONFIGURATION VARIABLES * * */
	    var disqus_shortname = 'janandrocket';
	    
	    /* * * DON'T EDIT BELOW THIS LINE * * */
	    (function() {
	        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
	        dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
	        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
	    })();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</div>

app/views/episodes/index.html.erb
<div class="page-heading"><h1>Previous Episodes</h1></div>
<div class="episodes-list">
	<% @episodes.each do |episode| %>
		<div class="episode"><!--#<%#= episode.id %>:--> <%= link_to(episode.title, episode_path(episode)) %></div>
	<% end %> 
</div>

app/views/episodes/show.html.erb
<div class="row">
	<div class="page-header small-12 medium-12 large-12 columns">
		<h1><!--Episode <%#= @episode.id %>: --><%= @episode.title %></h1>
	</div>
</div>
<div class="row">
	<div class="content small-12 medium-12 large-12 columns">
		<%= @episode.content.html_safe %>
	</div>
</div>
<div class="prev-next row">
	<div class="small-12 medium-12 large-12 columns">
		<script type="text/javascript">
			$(document).ready(function(){
				$('.oldest').click(function(e){
					alert("You're already at the oldest episode.");
					e.preventDefault();
				});
				$('.newest').click(function(e){
					alert("You're already at the newest episode.");
					e.preventDefault();
				});
			});
		</script>
		<%= nav_arrows(@id) %>
	</div>
</div>
<div class="row">
	<div class="comments small-12 medium-12 large-12 columns">
		<div id="disqus_thread"></div>
		<script type="text/javascript">
		    /* * * CONFIGURATION VARIABLES * * */
		    var disqus_shortname = 'janandrocket';
		    
		    /* * * DON'T EDIT BELOW THIS LINE * * */
		    (function() {
		         var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
		         dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
		         (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		    })();
		</script>
		<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
	</div>
</div>

app/views/layouts/_menu.html.erb
<div id="menu">
	<div class="show-for-large-up">
		<span class="home-link"><a href="/">Home</a></span>
		<span class="home-link"><a href="/terminology">Terminology</a></span>
		<span class="home-link"><a href="/characters">Characters</a></span>
		<div class="nav">
			<span class="menu-item"><a href="/#current">Current Episode</a></span>
			<span class="menu-item"><%= link_to("Past Episodes", episodes_path) %></span>
		</div>
	</div>
	<div class="hide-for-large-up">
		<a id="mnav-link" href="#">Menu</a>
		<ul id="mnav">
			<li class="banner-link"><%= link_to("Current Episode", Episode.where(:is_published => 1).last) %></li>
			<li class="banner-link"><%= link_to("Start at the Beginning", Episode.first) %></li>
			<li class="banner-link"><%= link_to("Past Episodes", episodes_path) %></li>
			<li class="banner-link"><a href="/terminology">Terminology</a></li>
			<li class="banner-link"><a href="/characters">Characters</a></li>
		</ul>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Adventures of Jan and Rocket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700italic,700|Oxygen:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
	<%= yield %>
</body>
</html>

app/views/layouts/episode.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Adventures of Jan and Rocket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700italic,700|Oxygen:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body class="episode">
	<%= render '/layouts/menu' %>
	<%= yield %>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67491748-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Adventures of Jan and Rocket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700italic,700|Oxygen:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
<div id="banner">
	<div class="row">
		<div class="small-12 medium-12 large-12 columns">
			<div class="row hide-for-large-up">
				<div class="small-12 medium-12 columns">
					<a id="mnav-link" href="#">Menu</a>
					<ul id="mnav">
						<li class="banner-link"><%= link_to("Current Episode", Episode.where(:is_published => 1).last) %></li>
						<li class="banner-link"><%= link_to("Start at the Beginning", Episode.first) %></li>
						<li class="banner-link"><%= link_to("Past Episodes", episodes_path) %></li>
						<li class="banner-link"><a href="/terminology">Terminology</a></li>
						<li class="banner-link"><a href="/characters">Characters</a></li>
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="small-1 medium-1 large-1 columns"></div>
				<div class="small-11 medium-11 large-11 columns">
					<h1>The Adventures of Jan and Rocket</h1>
				</div>
			</div>
			<div class="row show-for-large-up">
				<div class="large-12 columns">
					<ul id="home-nav">
						<li class="banner-link"><%= link_to("Current Episode", Episode.where(:is_published => 1).last) %></li>
						<li class="banner-link"><%= link_to("Start at the Beginning", Episode.first) %></li>
						<li class="banner-link"><%= link_to("Past Episodes", episodes_path) %></li>
						<li class="banner-link"><a href="/terminology">Terminology</a></li>
						<li class="banner-link"><a href="/characters">Characters</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<div id="home-content">
	<div class="row">
		<div class="small-12 medium-12 large-12 columns">
			<%= cms_block_content(:content).html_safe %>	
		</div>
	</div>
</div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67491748-1', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>

app/views/layouts/page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Adventures of Jan and Rocket</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,400italic,700italic,700|Oxygen:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Orbitron:400,500,700,900' rel='stylesheet' type='text/css'>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body class="page">
	<%= render '/layouts/menu' %>
	<div id="page-content" class="row">
		<div class="left-side small-12 medium-12 large-12 columns">
			<%= yield %>
		</div>
	</div>
  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-67491748-1', 'auto');
  ga('send', 'pageview');

</script>
</body>